image: docker:19.03.5
services:
  - docker:19.03.5-dind

stages:
  - Build
  - Push

Build:
  stage: Build
  script:
    - apk add python3
    - rm -rf dist/
    - python3 setup.py bdist_wheel sdist
  artifacts:
    name: dist
    paths:
      - dist/
  rules:
    - if: "$CI_COMMIT_TAG =~ /^*-release$/"

Push Release:
  stage: Push
  script:
    - pip install -U twine
    - export TAG=$(echo $CI_COMMIT_TAG | sed 's/-release//')
    - echo $TAG
    - python setup.py sdist
    - twine upload dist/*
  rules:
    - if: "$CI_COMMIT_TAG =~ /^*-release$/"

Push Github:
  stage: Push
  script:
    - apk add git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - mkdir -p ~/.ssh
    - touch ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\nStrictHostKeyChecking no\n" > ~/.ssh/config
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - git remote add github git@github.com:functionoffunction/influx-line.git
    - git branch --show-current
    - git push github HEAD:main
