image: docker:19.03.5
services:
  - docker:19.03.5-dind

stages:
  - Build
  - Push

Build:
  stage: Build
  script:
    - apk add python3
    - pip3 install twine
    - rm -rf dist/
    - python3 setup.py bdist_wheel sdist
  artifacts:
    name: dist
    paths:
      - dist/
  rules:
    - if: "$CI_COMMIT_TAG =~ /^*-release$/"

Push Release:
  stage: Push
  script:
    - export TAG=$(echo $CI_COMMIT_TAG | sed 's/-release//')
    - echo $TAG
  rules:
    - if: "$CI_COMMIT_TAG =~ /^*-release$/"

Push Github:
  stage: Push
  script:
    - apk add git
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git remote add github git@github.com:functionoffunction/influx-line.git
    - git branch --show-current
    - git push github HEAD:main

