image: docker:19.03.5
services:
  - docker:19.03.5-dind

stages:
  - Build
  - Push

Build:
  stage: Build
  script:
    - apk add python3
    - pip3 install twine
    - rm -rf dist/
    - python3 setup.py bdist_wheel sdist
  artifacts:
    name: dist
    paths:
      - dist/
  rules:
    - if: "$CI_COMMIT_TAG =~ /^*-release$/"

Push Release:
  stage: Push
  script:
    - export TAG=$(echo $CI_COMMIT_TAG | sed 's/-release//')
    - echo $TAG
  rules:
    - if: "$CI_COMMIT_TAG =~ /^*-release$/"

Push Github:
  stage: Push
  script:
    - apk add git
    - mkdir ~/.ssh
    - echo $private_key > ~/.ssh/id_rsa
    - git remote add github git@github.com:functionoffunction/influx-line.git
    - git status
    - git push github main

